name: cttns
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  circular_bottom_navigation: ^2.3.0
  mobx_triple: any
  flutter_mobx: any
  flutter_triple: ^2.0.0
  mobx: ^2.0.7+7
  woocommerce_api: ^0.1.0
  flutter_modular: ^5.0.3
  badges: ^3.1.1
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
